package org.profit.telegrambot.enums;


public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    CLICKED_ADD_CATEGORY,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    CHANGE_NAME,
    DELETE_PRODUCT,
    DELETE_CATEGORY,
    RENAME_CATEGORY,
    CHANGE_PRICE,
    IMAGE_SENT,
    CHANGE_DESCRIPTION,
    SHOW_PRODUCTS,
    UPDATE_PRODUCT,

}
