package org.profit.telegrambot.enums;

public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    CLICKED_ADD_CATEGORY,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    ENTERED_CATEGORY_NAME,

    CHANGE_NAME_BY_ID,
    CHANGE_NAME,
    DELETE_PRODUCT,
    DELETE_CATEGORY;

}
